language: php
php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  - SIMPLETEST_DB=sqlite://tmp/site.sqlite

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

script:
  # Test stable release
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  - ./../vendor/bin/phpunit -c core --exclude-group Composer
  - ./../vendor/bin/drush
  - ./../vendor/bin/console

  # Test dev release
  - cd $TRAVIS_BUILD_DIR
  - composer --verbose require --no-update drupal/core:8.0.x-dev
  - composer --verbose update
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  - ./../vendor/bin/phpunit -c core --exclude-group Composer
  - ./../vendor/bin/drush
  - ./../vendor/bin/console

  # Test site features
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install config_installer --verbose --yes --db-url=sqlite://tmp/site.sqlite -y --keep-config config_installer_staging_configure_form.sync_directory=../config/sync
  # Start webserver
  - nohup ./../vendor/bin/drush runserver --root=$TRAVIS_BUILD_DIR/web --server=builtin :9002 &
  # Start Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar
  - java -jar selenium-server-standalone-2.25.0.jar -p 4444 &
  # Run testsuite
  - cd $TRAVIS_BUILD_DIR
  - bin/behat