<?php

/**
 * @file
 * Defines default content for install purposes.
 */

/**
 * Implements hook_entity_type_build().
 *
 * Provides a canonical link template for paragraphs, so that they can be
 * normalized to HAL. HAL requires each entity do have a canonical URL.
 *
 * @see dbc16_default_content.routing.yml
 */
function dbcd16_default_content_entity_type_build(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  if (isset($entity_types['paragraph'])) {
    $entity_types['paragraph']->setLinkTemplate('canonical', '/paragraph/{paragraph}');
  }
}
